Show All Communities of filter list
massenergize/frontend-admin pull request #1015
Opened 2023-06-20 14:17 UTC by abdullai-t

####  This PR closes [issue](https://github.com/massenergize/frontend-admin/issues/1011)

#### Changes
- [x] Added a custom filter select component to all tables that is able to pull more communities from the backend.

#### Demo
https://github.com/massenergize/frontend-admin/assets/42780120/782a06cd-b2e3-4c78-9ff4-299a2ebdd838

2023-07-05 04:36 UTC, frimpongopoku requested changes
also @abdullai-t  conflicts

2023-07-05 04:36 UTC, frimpongopoku commented on app/utils/useObserver.js
@abdullai-t  we need comments here. Whats going on in "userObserver"? Whats the logic? And when you've explained the logic, how does anyone make use of "useObserver" anywhere else right away?

2023-07-05 04:36 UTC, frimpongopoku commented on app/utils/components/AsyncSelect/AsyncSelect.js
Again, same here, whats the concept. How does "AnySelect" work?  comments...? (You shouldnt be the only one that can easily make changes to this component 💀 )

2023-07-07 17:58 UTC, BradHN1 approved these changes
LGTM

2023-07-07 17:59 UTC, merged