fix: Add community list validation
massenergize/frontend-admin pull request #1135
Opened 2024-03-04 10:45 UTC by frimpongopoku

####  Summary / Highlights

#### Details (Give details about what this PR accomplishes, include any screenshots etc)

#### Testing Steps (Provide details on how your changes can be tested)

#### Requirements (place an `x` in each `[ ]`)
* [X] I've read and understood the [Contributing Guidelines](/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [X] I've tested my changes manually.
* [ ] I've added unit tests to my PR.

##### Transparency ([Project board](https://github.com/orgs/massenergize/projects/7/views/2))
* [X] I've given my PR a meaningful title.
* [ ] I linked this PR to the relevant issue.
* [ ] I moved the linked issue from the "Sprint backlog" to "In progress" when I started this.
* [ ] I moved the linked issue to "QA Verification" now that it is ready to merge.

- [X] It now checks if communities are selected before you are allowed to continue

2024-03-04 15:50 UTC, archx3 requested changes

2024-03-04 15:50 UTC, archx3 commented on app/containers/MassEnergizeSuperAdmin/Events/notifcation-settings/EventNotificationSettings.js
>      const isALL = targetCommunities?.find((c) => typeof c === "string" && c?.toLowerCase() === "all");
can you use a more descriptive names here to make the code more self documenting?
The function name `readyForFlight` doesn't seem to tell what it does, neither does the variable name `c` on line 118

2024-03-05 13:45 UTC, archx3 approved these changes

2024-03-05 13:46 UTC, merged

2024-04-22 18:38 UTC, boatengjephthah27 commented
There is nothing describing the issue that was fixed, 
no link to the issue and no better description of the problem
Currently it is hard determining the fix that was made @frimpongopoku

2024-04-23 11:30 UTC, frimpongopoku commented
> There is nothing describing the issue that was fixed, no link to the issue and no better description of the problem Currently it is hard determining the fix that was made @frimpongopoku

This is related to event notification settings (new feature). Its not a bug fix.