Sadmin feature flags implementation
massenergize/frontend-admin pull request #637
Opened 2022-07-13 09:08 UTC by frimpongopoku

This works with [API PR](https://github.com/massenergize/api/pull/531)

- [ ] Only sadmins have access to feature flags for now 
Sadmins can 

1. Create Feature Flag on the portal 
2. Can edit feature flags 
3. Delete feature flags 
4. Also define the which communities, platform, and which users a flag is for 

Video Eg. 

https://user-images.githubusercontent.com/26961591/178695814-a581c124-90f1-492b-8201-659d58a9d9ec.mov

2022-08-04 18:57 UTC, BradHN1 commented on app/redux/redux-actions/adminActions.js
> +    apiCall("/featureFlags.list_for_super_admins"),
change to featureFlags.listForSuperAdmin

2022-08-04 19:07 UTC, BradHN1 commented on app/containers/MassEnergizeSuperAdmin/Feature Flags/AddOrEditFeatureFlags.js
> +  if (!flagKeys || !flagKeys.audience) return <Loading />;
this was causing infinite loop during testing, since the api call had returned nothing

2022-08-04 19:09 UTC, BradHN1 commented on app/containers/MassEnergizeSuperAdmin/Feature Flags/AddOrEditFeatureFlags.js
> +        label: "Feature Deactivation",
Should be a separate field:
This feature does not expire   (default)
This feature expires after date

then if they choose the second radio button, they can enter the date.
Right now, a date gets added and it isn't clear how to delete it.

2022-08-04 19:10 UTC, BradHN1 commented on app/containers/MassEnergizeSuperAdmin/Feature Flags/ManageFeatureFlags.js
> +  if (!flags) return <Loading />;
this line leads to infinite spinner if no flags exist.  Leave out.

2022-08-04 19:11 UTC, BradHN1 commented on app/containers/MassEnergizeSuperAdmin/Feature Flags/ManageFeatureFlags.js
> +const hasExpired = (date) => {
if no date supplied, the routine should return hasExpired=false

2022-08-04 19:19 UTC, BradHN1 requested changes
Minor changes requested

2022-08-05 03:55 UTC, frimpongopoku commented
Thanks, will look into them 👍🏾

2022-08-09 05:44 UTC, frimpongopoku commented
@BradHN1  
https://user-images.githubusercontent.com/26961591/183573314-4bcc1d99-1820-450e-ad08-e990d5eeb594.mov

2022-08-09 14:42 UTC, merged